<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="GCTHW5H2E" name="org.ge.dctests.Sample" tests="6" failures="1" timestamp="12 Mar 2018 06:57:18 GMT" time="521.408" errors="0">
  <testcase name="dcEventSubjectRule" time="521.408" classname="org.ge.dctests.Sample">
    <failure type="java.lang.AssertionError" message="Event is not displayed on the gantt expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Event is not displayed on the gantt expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.ge.dctests.Sample.dcEventSubjectRule(Sample.java:127)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- dcEventSubjectRule -->
  <testcase name="dcDispatchHoverRule" classname="org.ge.dctests.Sample">
    <skipped/>
  </testcase> <!-- dcDispatchHoverRule -->
  <testcase name="dcDispatchHoverRule2" classname="org.ge.dctests.Sample">
    <skipped/>
  </testcase> <!-- dcDispatchHoverRule2 -->
  <testcase name="dcDispatchVIewRule2" classname="org.ge.dctests.Sample">
    <skipped/>
  </testcase> <!-- dcDispatchVIewRule2 -->
  <testcase name="createEvent" classname="org.ge.dctests.Sample">
    <skipped/>
  </testcase> <!-- createEvent -->
  <testcase name="locateTechMapRoute" classname="org.ge.dctests.Sample">
    <skipped/>
  </testcase> <!-- locateTechMapRoute -->
</testsuite> <!-- org.ge.dctests.Sample -->
